--- # Set DNS for netplan configuration

- hosts: "{{ hosts }}"
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  roles:
  - kwoodson.yedit

  tasks:
  - name: manage yaml files
    yedit:
      src: /etc/netplan/50-cloud-init.yaml
      key: network.ethernets.ens160
      value:
        dhcp4: true
        nameservers:
          addresses: [1.2.3.4, 5.6.7.8]

  - name: apply changes
    command: "netplan apply"
