--- # Login to private registry

- hosts: "{{ hosts }}"
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:
  - name: add registry host
    lineinfile:
      dest: /etc/hosts
      regexp: ''
      insertafter: EOF
      line: '{{ docker_registry_ip }} {{ docker_registry_address }}'

  - name: add insecure registry
    copy:
      content: |
               {
                   "insecure-registries" : [ "{{ docker_registry_address }}" ]
               }
      dest: /etc/docker/daemon.json

  - name: Reload docker service
    service:
      name: docker
      state: reloaded

  - name: login to private registry
    docker_login:
      registry: "http://{{ docker_registry_address }}"
      username: "{{ docker_registry_username }}"
      password: "{{ docker_registry_password }}"
      validate_certs: false
