--- # Install Nginx

- name: Install nginx
  hosts: '{{ hosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Insert Index Page
      template:
        src: index.html
        dest: /var/www/html/index.nginx-debian.html

    - name: Start NGiNX
      service:
        name: nginx
        state: started
