# Install Docker & Docker-compose

- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  tags:
    - docker

- name: Verify that we have the key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  tags:
    - docker
 
- name: Set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  tags:
    - docker
 
- name: Update apt packages
  apt:
    update_cache: yes
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  tags:
    - docker
  
- name: Install docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
  tags:
    - docker
 
- name: Add remote "ansible" user to "docker" group
  user:
    name: "ansible"
    group: "docker"
    append: yes
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  tags:
    - docker
