--- # Initialize master node 

- hosts: master
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  
  tasks:
  - name: Remove debug file
    file:
      path: $HOME/cluster_initialized.txt
      state: absent

  - name: Initialize the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
    args:
      chdir: $HOME
      creates: cluster_initialized.txt

  - name: Create .kube directory
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755
  
  - name: Copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes
      owner: ansible
  
  - name: Remove debug file
    file:
      path: $HOME/pod_network_setup.txt
      state: absent
  
  - name: Install Pod network
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
    args:
      chdir: $HOME
      creates: pod_network_setup.txt
    retries: 3
    delay: 10
    register: result
    until: result is succeeded