--- # Uninstall Redis

- name: Uninstall nginx
  hosts: '{{ hosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Stop redis
      service:
        name: redis
        state: stopped

    - name: Remove file and directories
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/systemd/system/redis.service
        - /etc/redis/redis.conf
        - /etc/rc.local
        - /etc/redis
        - /var/lib/redis
        - /var/log/redis
        - /var/run/redis

    - name: Get users list
      shell: 'cut -d: -f1 /etc/passwd'
      register: user_data

    - name: remove redis user from redis group
      command: "deluser redis"
      when: user_data is defined and 'redis' in user_data

    - name: Get groups list
      shell: 'cut -d: -f1 /etc/group'
      register: group_data

    - name: remove redis group
      command: "gpasswd -d redis redis"
      when: group_data is defined and 'redis' in group_data
